### ISSUE TITLE
Bounding box not kept during rotation

### ISSUE THREAD

**Issue by GlenHertz** [GiovineItalia/Compose.jl#178]
Hi,

Running on today's master when I rotate the rotation does its job but the bounding box is expanded.  If I try the following example in JuliaBox:

``` Julia
using Compose 
points_f = [
    (.1, .1),
    (.9, .1),
    (.9, .2),
    (.2, .2),
    (.2, .4),
    (.6, .4),
    (.6, .5),
    (.2, .5),
    (.2, .9),
    (.1, .9),
    (.1, .1)
]

f = compose(context(), stroke("black"), line(points_f))
rot(pic) = compose(context(rotation=Rotation(-deg2rad(90))), pic)
zoomout(pic) = compose(context(),
                      (context(0.2, 0.2, 0.6, 0.6), pic),
                      (context(0.2, 0.2, 0.6, 0.6), fill(nothing), stroke("black"), strokedash([0.5mm, 0.5mm]),
                      polygon([(0, 0), (1, 0), (1, 1), (0, 1)])))
f |> zoomout
rot(f) |> zoomout
```

The "F" is out of the visible area (and it can be seen with "zoomout").  This example comes from the excellent [Functional Geometry](https://shashi.github.io/ijulia-notebooks/funcgeo/) example which is excellent for learning this library (which you can see it gets a different result for rotation).

**Comment by nowozin** [comment]
I can reproduce this.
It seems to be a regression because [Shashi's example notebook output](https://shashi.github.io/ijulia-notebooks/funcgeo/) does not suffer from this despite using the same commands.

In fact, I stumbled across this issue by running the simpler case:
```julia
using Compose

points_f = [
    (.1, .1),
    (.9, .1),
    (.9, .2),
    (.2, .2),
    (.2, .4),
    (.6, .4),
    (.6, .5),
    (.2, .5),
    (.2, .9),
    (.1, .9),
    (.1, .1)
]

f = compose(context(), stroke("black"), line(points_f))
rot(pic) = compose(context(rotation=Rotation(-π/2)), pic)
rot(f)
```

This will produce just a blank output and I was a bit lost.  This issue explains what happens.

**Comment by nowozin** [comment]
In trying to track this down, I have looked at the following:

- It is not a property of the output format used.  The following code, modified from the original example above, produces the same (wrong) figure for SVG/PDF/SVGJS:
```julia
using Compose

points_f = [
    (.1, .1), (.9, .1), (.9, .2), (.2, .2),
    (.2, .4), (.6, .4), (.6, .5), (.2, .5),
    (.2, .9), (.1, .9), (.1, .1)
]   

f = compose(context(), stroke("black"), line(points_f))
zoomout(pic) = compose(
    context(),
    (context(0.3, 0.3, 0.4, 0.4), pic),
    (context(0.3, 0.3, 0.4, 0.4), fill(nothing), stroke("black"), strokedash([0.5mm, 0.5mm]),
        polygon([(0, 0), (1, 0), (1, 1), (0, 1)])))
    
frot = zoomout(compose(context(rotation=Rotation(0.9, (0.5w, 0.5h))), f))

imgs = [PDF("rotationtest.pdf", 3cm, 3cm),
    SVG("rotationtest.svg", 3cm, 3cm),
    SVGJS("rotationtest.js", 3cm, 3cm)]
    
for img = imgs
    draw(img, frot)
end
```

- I looked at the rotation matrix used in `measure.jl` and it is correctly computed as a result of the product of three matrices (translate-rotate-translate).

This must be a regression because it worked in Shashi's example code (using the same rotations).
Did this perhaps break in the 0.3 to 0.4 transition?

**Comment by nowozin** [comment]
News:

- Using Julia 0.3.12 the above program works and produces a rotated figure positioned in the center of the box.
- Using Julia 0.4.2 the above program fails, i.e. it produces a rotated figure where the symbol is shifted outside of the box.

Therefore, this error could originate from a subtle change in syntax between 0.3 and 0.4.
