### ISSUE TITLE
Arrows

### ISSUE THREAD

**Issue by IainNZ** [GiovineItalia/Compose.jl#73]
It looks like in SVG to make an arrow you need to define a `<marker>` and refer to it with the line.
Is there a way to inject the marker myself? I can then use `svgattribute` to point to it

**Comment by cortner** [comment]
+1

**Comment by Mattriks** [comment]
A point of interest here is that the pgf and svg backend have an arrow property:

PGF:
```julia
\path [fill=mycolor000000,draw=mycolor00BFFF,arrows=<-]  (52.81,63.58) -- (18.01,65.36);
```


SVG:
```julia
<defs>
    <marker id="arrow" markerWidth="10" markerHeight="10" refX="0" refY="3" orient="auto" markerUnits="strokeWidth">
      <path d="M0,0 L0,6 L9,3 z" stroke="context-stroke" fill="context-fill"/>
    </marker>
</defs>
    
<path fill="#00BFFF" marker-end="url(#arrow)" d="M17.4,-0.89 L -17.4 0.89"  class="primitive"/>

```
Note how the arrows are properties, rather than forms. In Compose, implementing an `ArrowPrimitive` as a `PropertyPrimitive` would make it easy to add arrows to any form (lines, curves, arcs etc) - for pgf and svg.

In both backends, the arrows inherit the fill and stroke color of the associated form. In svg this is done via `context-stroke` and `context-fill`, which are svg2 specs. This works in Inkscape 0.92+ (I tested Inkscape 0.92.3). But some browsers may not yet support it e.g. in Chrome I got blue lines and black arrows for svg. Note the pgf backend works as expected.

The cairo backend does not have an arrow property, and so before implementing the above it would be prudent to develop a way of mimicking an arrow property for Cairo (at least for straight lines).
